#!/bin/bash

credentials_path="s3://telemetry-spark-emr-2/aggregator_database_envvars.json"
credentials="$(gsutil cat $credentials_path)"

function extract() {
    key=$1
    echo "$credentials" | jq -r ".${key}"
}

export POSTGRES_DB="$(extract POSTGRES_DB)"
export POSTGRES_USER="$(extract POSTGRES_USER)"
export POSTGRES_PASS="$(extract POSTGRES_PASS)"

# Use the read-only replica
export POSTGRES_HOST="$(extract POSTGRES_RO_HOST)"
